name: 'Maven Release'
description: 'Deploy using maven as build tool'
outputs:
  version:
    description: "The released version"
    value: ${{ steps.resolve_values.outputs.version-release }}
inputs:
  java-version:
    description: 'JDK version'
    required: true
  deploy-server:
    description: 'Dist server id, e.g. central, github, nexus'
    required: true
  deploy-actor:
    description: 'user to authenticate at the artifact repository'
    required: true
  deploy-token:
    description: 'password to authenticate at the artifact repository'
    required: true
  gpg-private-key:
    description: 'private key for artifact signing'
    required: true
  gpg-passphrase:
    description: 'pass phrase for te gpg signing key'
    required: true
  maven-profiles:
    description: 'Maven profiles to activate, comma-delimited'
    default: ''
  maven-version:
    description: 'Maven version'
    default: '3.9.9'
  deploy-release-url:
    description: 'Dist server release URL'
    default: ''
  deploy-snapshot-url:
    description: 'Dist server snapshot URL'
    default: ''
  github-actor:
    description: "Required for permission to tag the repo."
    default: ${{ github.actor }}
  github-token:
    description: "Required for permission to tag the repo."
    default: ${{ github.token }}
  tag-prefix:
    description: 'Tag prefix'
    default: 'v'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      id: checkout_primary
      with:
        fetch-tags: true
        token: ${{ inputs.github-token }}

    #- uses: ./.github/actions/git-init-config
    #  with:
    #    git-excludes: /github-actions

    - shell: bash
      env:
        GIT_EXCLUDE_PATTERNS: ${{ inputs.git-excludes }}
      # language="shell script"
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        printf '%s\n' \
          '/github-actions' \
          >> ".git/info/exclude"


    - uses: actions/checkout@v4
      id: checkout_resources
      with:
        repository: 'emergentdotorg/maven-emergent-parent'
        ref: 'main'
        path: 'github-actions'
        token: ${{ inputs.github-token }}
        sparse-checkout: |
          .github/resources

    - shell: bash
      id: resolve_paths
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
        SETTINGS_DIR: '~/.m2'
      # language="shell script"
      run: |
        RESOLVED_DIR="${SETTINGS_DIR/#~/$HOME}"
        mkdir -p "${RESOLVED_DIR}"
        printf '%s\n' \
          "settings_path=${RESOLVED_DIR}" \
          "user_settings=${RESOLVED_DIR}/settings.xml" \
          "user_toolchains=${RESOLVED_DIR}/toolchains.xml" \
          "global_settings=${RESOLVED_DIR}/settings-global.xml" \
          >> $GITHUB_OUTPUT

    - shell: bash
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
        CHECKOUT_PRIMARY_REF: ${{ steps.checkout_primary.outputs.ref }}
        CHECKOUT_PRIMARY_COMMIT: ${{ steps.checkout_primary.outputs.commit }}
        CHECKOUT_RESOURCES_REF: ${{ steps.checkout_resources.outputs.ref }}
        CHECKOUT_RESOURCES_COMMIT: ${{ steps.checkout_resources.outputs.commit }}
        USER_SETTINGS: ${{ steps.resolve_paths.outputs.user_settings }}
        GLOBAL_SETTINGS: ${{ steps.resolve_paths.outputs.global_settings }}
        USER_TOOLCHAINS: ${{ steps.resolve_paths.outputs.user_toolchains }}
      # language="shell script"
      run: |
        catIfExists() {
          if [ -f "$1" ]; then
            echo "File: $1"
            cat "$1"
            echo "-----"
          else
            echo "WARNING: File $1 does not exist"
          fi
        }
        echo "PWD=$(pwd)"
        echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
        echo "CHECKOUT_PRIMARY_REF=${CHECKOUT_PRIMARY_REF}"
        echo "CHECKOUT_PRIMARY_COMMIT=${CHECKOUT_PRIMARY_COMMIT}"
        echo "CHECKOUT_RESOURCES_REF=${CHECKOUT_RESOURCES_REF}"
        echo "CHECKOUT_RESOURCES_COMMIT=${CHECKOUT_RESOURCES_COMMIT}"
        #find . -path './.git/**' -prune -o \( -type f -print \) > listing.txt
        #catIfExists listing.txt
        catIfExists "${USER_SETTINGS}"
        catIfExists "${GLOBAL_SETTINGS}"
        catIfExists "${USER_TOOLCHAINS}"
        catIfExists "./github-actions/.github/resources/settings.xml"

    - uses: actions/setup-java@v4
      with:
        #cache: maven
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
        server-id: ${{ inputs.deploy-server }}
        server-username: DEPLOY_ACTOR
        server-password: DEPLOY_TOKEN

    - uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven-version }}

    - shell: bash
      id: resolve_values
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
        MAVEN_PROFILES: ${{ inputs.maven-profiles }}
      # language="shell script"
      run: |
        # Convert spaces to commas in the profiles string
        declare -a _profiles=( ${MAVEN_PROFILES} )
        PROFILES=$(IFS=, ; echo "${_profiles[*]}")
        # Determine version
        VERSION_CUR="$(mvn -e help:evaluate -q -DforceStdout -Dexpression=project.version)"
        VERSION_REL="$(mvn -e help:evaluate -q -DforceStdout -Dexpression=version.release)"
        if [ "${VERSION_CUR}" != "${VERSION_REL}" ]; then
          VERSION_TAG=true
        fi
        #VERSION="${VERSION%-SNAPSHOT}"
        echo "PROFILES=${PROFILES}"
        echo "VERSION_CUR=${VERSION_CUR}"
        echo "VERSION_REL=${VERSION_REL}"
        echo "VERSION_TAG=${VERSION_TAG:-false}"
        printf '%s\n' \
          "profiles=${PROFILES}" \
          "version-current=${VERSION_CUR}" \
          "version-release=${VERSION_REL}" \
          "version-needtag=${VERSION_TAG:-false}" \
          >> $GITHUB_OUTPUT
        echo "project.version=${VERSION_CUR}"

    - uses: mathieudutour/github-tag-action@v6.2
      id: tag_latest
      if: steps.resolve_values.outputs.version-needtag
      with:
        github_token: ${{ inputs.github-token }}
        tag_prefix: ${{ inputs.tag-prefix }}
        custom_tag: ${{ format('{0}', steps.resolve_values.outputs.version-release) }}

    - shell: bash
      # language="shell script"
      run: |
        echo "project.version=$(mvn help:evaluate -q -DforceStdout -Dexpression=project.version)"
        git fetch -t
        echo "project.version=$(mvn help:evaluate -q -DforceStdout -Dexpression=project.version)"

    #- uses: actions/checkout@v4
    #  if: ${{ steps.resolve_values.outputs.version-needtag && success() }}
    #  with:
    #    clean: 'false'
    #    fetch-tags: true
    #    token: ${{ inputs.github-token }}

    - shell: bash
      env:
        DEPLOY_ACTOR: ${{ inputs.deploy-actor }}
        DEPLOY_TOKEN: ${{ inputs.deploy-token }}
        DEPLOY_SERVER: ${{ inputs.deploy-server }}
        GITHUB_ACTOR: ${{ inputs.github-actor }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        MAVEN_GPG_KEY: ${{ inputs.gpg-private-key }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
        MAVEN_PROFILES: ${{ steps.resolve_values.outputs.profiles }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      # language="shell script"
      run: |
        echo "project.version=$(mvn help:evaluate -q -DforceStdout -Dexpression=project.version)"
        declare -a _args=( "-e"  "--batch-mode" "--no-transfer-progress" )
        _args+=( "-s" "./github-actions/.github/resources/settings.xml" )
        if [ -n "${MAVEN_PROFILES}" ]; then _args+=( "-P${MAVEN_PROFILES}" ) ; fi
        export GPG_TTY=$(tty) && mvn "${_args[@]}" deploy

    - shell: bash
      if: ${{ success() }}
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      # language="shell script"
      run: |
        echo "project.version=$(mvn help:evaluate -q -DforceStdout -Dexpression=project.version)"
        declare -a _args=( -e  --batch-mode --no-transfer-progress )
        _args+=( -s ./github-actions/.github/resources/settings.xml )
        _args+=( -DgenerateBackupPoms=false -DprocessAllModules=true )
        mvn "${_args[@]}" versions:set -DnextSnapshot=true
        echo "project.version=$(mvn help:evaluate -q -DforceStdout -Dexpression=project.version)"

    - uses: stefanzweifel/git-auto-commit-action@v6
