name: 'Bump and Tag'
description: 'Increment the version and tag'

inputs:
  github-token:
    description: "Required for permission to tag the repo."
    required: true
  tag-bump:
    description: 'Tag bump'
    default: 'patch'
  tag-prefix:
    description: 'Tag prefix'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true

    - name: Setup Git User
      shell: bash
      # language="shell script"
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Increment and Tag Version
      if: ${{ inputs.tag-bump != '' }}
      id: tag_latest
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ inputs.github-token }}
        default_bump: ${{ inputs.tag-bump }}
        tag_prefix: ${{ inputs.tag-prefix }}
