name: Maven Release

on:
  workflow_dispatch:
    inputs:
      deploy-server:
        description: 'Distribution server-id'
        type: choice
        required: false
        default: emergent-nexus
        options:
          - central
          - github
          - emergent-github
          - emergent-nexus
      push-changes:
        description: 'Push commits during the maven release goal execution'
        type: boolean
        required: false
        default: true
      dry-run:
        description: 'Dry-run without commits or deploys'
        type: boolean
        required: false
        default: false

jobs:
  invoke-release:
    uses: emergentdotorg/github-actions/.github/workflows/maven-release.yaml@v3
    secrets: inherit
    with:
      java-version: '8'
      maven-profiles: 'emergent-release'
      deploy-server: ${{ inputs.deploy-server }}
      push-changes: ${{ inputs.push-changes }}
      dry-run: ${{ inputs.dry-run }}

  process-results:
    runs-on: ubuntu-latest
    needs: invoke-release
    steps:
      - run: echo version=${{ needs.invoke-release.outputs.version }}
