name: Maven Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  invoke-release:
    uses: ./.github/workflows/reusable-maven-release.yml
    secrets: inherit
    with:
      java-version: '8'

  process-results:
    runs-on: ubuntu-latest
    needs: invoke-release
    steps:
      - run: echo version=${{ needs.invoke-release.outputs.version }}
