name: Maven Release

on:
  workflow_dispatch:
    inputs:
      server-id:
        description: 'Distribution server-id'
        type: choice
        required: false
        default: central
        options:
          - central
          - github
      maven-push-changes:
        description: 'Push commits during the maven release goal execution'
        type: boolean
        required: false
        default: true
      dry-run:
        description: 'Dry-run without commits or deploys'
        type: boolean
        required: false
        default: false

jobs:
  invoke-release:
    uses: emergentdotorg/github-actions/.github/workflows/maven-release.yaml@v1
    secrets: inherit
    with:
      java-version: '8'
      server-id: ${{ inputs.server-id }}
      maven-push-changes: ${{ inputs.maven-push-changes }}
      dry-run: ${{ inputs.dry-run }}

  process-results:
    runs-on: ubuntu-latest
    needs: invoke-release
    steps:
      - run: echo version=${{ needs.invoke-release.outputs.version }}
