name: Maven Deploy

on:
  workflow_dispatch:
    inputs:
      deploy-server:
        description: 'Distribution server-id'
        type: choice
        default: emergent-nexus
        options:
          - central
          - github
          - emergent-github
          - emergent-nexus
      push-changes:
        description: 'Push commits during the maven release goal execution'
        type: boolean
        default: true
      dry-run:
        description: 'Dry-run without commits or deploys'
        type: boolean
        default: false

jobs:
  invoke-deploy:
    uses: ./.github/workflows/maven-deploy_.yaml
    secrets: inherit
    with:
      java-version: '11'
      deploy-server: ${{ inputs.deploy-server }}

  process-results:
    runs-on: ubuntu-latest
    needs: invoke-deploy
    steps:
      - run: echo version=${{ needs.invoke-deploy.outputs.version }}
