name: Reusable Maven Deploy

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      version:
        description: "The new release version"
        value: ${{ jobs.deploy.outputs.version }}
    inputs:
      java-version:
        description: 'JDK version to build with'
        type: string
        required: true
      deploy-server:
        description: 'Maven dist mgmt server-id'
        type: string
        required: true
      maven-profiles:
        description: 'Maven profiles to activate, comma-delimited'
        type: string
        default: ''
      tag-bump:
        description: 'Tag bump, e.g. patch, etc.'
        type: string
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      version: ${{ steps.maven_deploy.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Bump and Tag
        if: ${{ inputs.tag-bump != '' }}
        id: bump_and_tag
        uses: ./.github/actions/bump-and-tag
        with:
          tag-bump: ${{ inputs.tag-bump }}
          github-token: ${{ github.token }}

      - name: Resolve Vars
        id: resolve_vars
        shell: bash
        env:
          DEPLOY_SERVER: ${{ inputs.deploy-server }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          DEPLOY_CENTRAL_ACTOR: ${{ secrets.deploy_central_actor }}
          DEPLOY_CENTRAL_TOKEN: ${{ secrets.deploy_central_token }}
          DEPLOY_GITHUB_ACTOR: 'emergentbot'
          DEPLOY_GITHUB_TOKEN: ${{ secrets.emergentbot_deploy_token }}
          DEPLOY_EMERGENT_NEXUS_ACTOR: ${{ secrets.deploy_emergent_nexus_actor }}
          DEPLOY_EMERGENT_NEXUS_TOKEN: ${{ secrets.deploy_emergent_nexus_token }}
        # language="shell script"
        run: |
          case "${DEPLOY_SERVER}" in
            central)
              DEPLOY_ACTOR="${DEPLOY_CENTRAL_ACTOR}"
              DEPLOY_TOKEN="${DEPLOY_CENTRAL_TOKEN}"
              ;;
            github)
              DEPLOY_ACTOR="${{ github.actor }}"
              DEPLOY_TOKEN="${{ github.token }}"
              DEPLOY_RELEASE_URL="https://maven.pkg.github.com/emergentdotorg/${GITHUB_REPOSITORY}"
              DEPLOY_SNAPSHOT_URL="https://maven.pkg.github.com/emergentdotorg/${GITHUB_REPOSITORY}"
              ;;
            emergent-github)
              DEPLOY_ACTOR="${DEPLOY_GITHUB_ACTOR}"
              DEPLOY_TOKEN="${DEPLOY_GITHUB_TOKEN}"
              DEPLOY_RELEASE_URL="https://maven.pkg.github.com/emergentdotorg/maven-repository"
              DEPLOY_SNAPSHOT_URL="https://maven.pkg.github.com/emergentdotorg/maven-repository"
              ;;
            emergent-nexus)
              DEPLOY_ACTOR="${DEPLOY_EMERGENT_NEXUS_ACTOR}"
              DEPLOY_TOKEN="${DEPLOY_EMERGENT_NEXUS_TOKEN}"
              DEPLOY_RELEASE_URL="https://nexus.emergent.org/repository/maven-releases/"
              DEPLOY_SNAPSHOT_URL="https://nexus.emergent.org/repository/maven-snapshots/"
              ;;
            *)
              ;;
          esac
          printf '%s\n' \
            "deploy-actor=${DEPLOY_ACTOR}" \
            "deploy-token=${DEPLOY_TOKEN}" \
            "deploy-release-url=${DEPLOY_RELEASE_URL}" \
            "deploy-snapshot-url=${DEPLOY_SNAPSHOT_URL}" \
            >> $GITHUB_OUTPUT

      - name: Maven Deploy
        id: maven_deploy
        uses: ./.github/actions/maven-deploy
        with:
          java-version: ${{ inputs.java-version }}
          maven-profiles: ${{ inputs.maven-profiles }}
          deploy-server: ${{ inputs.deploy-server }}
          deploy-actor: ${{ steps.resolve_vars.outputs.deploy-actor }}
          deploy-token: ${{ steps.resolve_vars.outputs.deploy-token }}
          deploy-release-url: ${{ steps.resolve_vars.outputs.deploy-release-url }}
          deploy-snapshot-url: ${{ steps.resolve_vars.outputs.deploy-snapshot-url }}
          gpg-passphrase: ${{ secrets.maven_gpg_passphrase }}
          gpg-private-key: ${{ secrets.maven_gpg_key }}

