name: Maven Verify

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: emergentdotorg/github-actions/.github/workflows/maven-verify.yaml@v2
    secrets: inherit
    with:
      java-version: '8'
