name: Tag and Release

on:
  #push:
  #  branches:
  #    - main
  #    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump and Tag
        id: bump_tag
        uses: ./.github/actions/bump-and-tag
        with:
          tag-bump: 'patch'
          github-token: ${{ github.token }}
